### ISSUE TITLE
戻り値の推測

### ISSUE THREAD

**Issue by junk0612** [UnicoenProject/UniMapperGenerator#14]
ルールにアノテーションを付ける際、戻り値を書かなくても子ノードにするフィールド名から推測して補うようにする。

**Comment by junk0612** [comment]
フィールド名からのみでは推測できない場合は？
1. 「推測できない」として戻り値を書かせる
2. ルール名などからなんとか推測しようとする

**Comment by junk0612** [comment]
推測はひとまずフィールド名からのみとする。
推測できない場合はエラーを吐く。

**Comment by junk0612** [comment]
子ノードの情報が散らばっている場合は？
(ex. `int a[] = new int[3];`: `int`と`[]`が両方typeにあたる)

**Comment by exKAZUu** [comment]
例えば、以下のような場合は、`classModifier`の戻り値は、`UniClassDec`の`modifiers`に代入されるという情報がわかった時点で、型が決まりインスタンス化できる。
したがって、 `classModifiers => List<String>` の戻り値の型は不要なはず。

```
normalClassDeclaration => UniClassDec
    :   classModifiers$modifiers 'class' className$className typeParameters?
        superclass?$superClass superinterfaces?$interfaces classBody$members
    ;

className => String
    :   Identifier
    ;

classModifiers => List<String>
    :   classModifier*$ADD
    ;

classModifier => String
    :   annotation
    |   'public'
    |   'protected'
    |   'private'
    |   'abstract'
    |   'static'
    |   'final'
    |   'strictfp'
    ;
```

**Comment by junk0612** [comment]
`List`に関しては、
- ADDがつけられたノードをリストで持っておく(ex: `{"add" : [children1, children2, ...]}`)
- 戻った先のノードがListであるはずなので`castToList`メソッドによってListに変換されフィールドに代入される
  という方法によって実現している。

**Comment by exKAZUu** [comment]
そもそも実装済み。
