### ISSUE TITLE
UniFor, UniWhile, UniDoWhileノードのフィルド

### ISSUE THREAD

**Issue by khlee12** [UnicoenProject/UniMapperGenerator#15]
現在のUniForノードのフィルドは

```
public UniExpr init;
public UniExpr cond;
public UniExpr step;
public UniExpr statement;
```

の四つで構成されているが、
statementのタイプはUniExprよりはUniBlockにしたほうが良いと思う。
同じくUniWhileとUniDoWhileのstatementも今は全部UniExprである。

**Comment by junk0612** [comment]
UniBlockはUniExprを継承しているので問題なく代入できるし、for文はBlockの形にならない

```
for(int i = 0; i < n; i++) a[i] = 0;
```

みたいなのもあったりするので、どうしてもBlockでなければならない理由がなければUniExprで良いと思っています(他のノードについても同様です)。

**Comment by khlee12** [comment]
ありがとうござます！
じゃあ、なぜUniIfのtrueStatementとfalseStatementはUniBlockとして扱っているのでしょうか？

**Comment by junk0612** [comment]
今手元で確認してみたんですが、UniExprになっていました。
すみませんが、どのブランチの話でしょうか？

**Comment by khlee12** [comment]
分かりました！すみません、ちょっと間違って理解してしまったらしいです。
今は大丈夫です、ありがとうございます！
また、UniIfとUniUnaryOpをAnnotationに追加し、テストも一通り通ってますが、
JUnicoenのkhleeのブランチにプルしてもいいでしょうか？

**Comment by junk0612** [comment]
`mvn test`がsuccessになるなら問題ないです。
今はkhleeのブランチで作業していますか？
もしそうならそのままcommitしてpushすれば大丈夫ですが、もしそうでないならブランチを切り替えてからcommitするのを忘れないように気をつけてください。

**Comment by khlee12** [comment]
一応今のマッパーはまだlocalVariableDeclarationの多重使用の問題が解決されてないバージョンです。
なので、テストはまだ成功できません。
前もその理由で新しくブランチを切りましたが、今回もそのままkhleeでプルしたらよろしいでしょうか？

**Comment by junk0612** [comment]
ああ、なるほど。
それでも自分のブランチなら大丈夫なので、そのままpushしてください。

**Comment by khlee12** [comment]
オッケーです！
